version: '3'

services:
  php:
    container_name: php-bakkhos
    build:
      context: ./docker/php
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    networks: 
      - bakkhos-network

networks:
  bakkhos-network:
    driver: bridge